version: '3.3'

services:

  web:
    image: "nginx:1.11-alpine"
    container_name: yona-cms-www
    ports:
      - "3500:80"
    volumes:
      - ./:/yona-cms
      - ./docker/log:/var/log/nginx
      - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/conf/php.ini:/etc/php/7.1/fpm/php.ini
    links:
      - php7

  php7:
    build: ./docker/php7/
    container_name: yona-cms-php7
    volumes:
      - ./:/yona-cms
      - ./docker/conf/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    environment:
      - TERM=xterm
      - APPLICATION_ENV=development
      - PHINX_ENVIRONMENT=development
    links:
      - mysql

  mysql:
    image: "mariadb:10.1.21"
    container_name: yona-cms-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111
      - MYSQL_DATABASE=yona-cms
      - MYSQL_USER=root
      - MYSQL_PASSWORD=111
    volumes:
      - ./docker/data/mysql-data:/var/lib/mysql
      - ./:/yona-cms

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: yona-cms-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - MYSQL_ROOT_PASSWORD=111
     - MYSQL_USER=root
    ports:
     - "3501:80"